MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 0
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 1280
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 20
    CHECKPOINT_PERIOD: 5
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5
    
  STAGE2:
    IMS_PER_BATCH: 1280
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00005
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 30
    CHECKPOINT_PERIOD: 5
    LOG_PERIOD: 50
    EVAL_PERIOD: 10
    BIAS_LR_FACTOR: 2
    
    STEPS: [30, 50]
    GAMMA: 0.1
  
TEST:
  EVAL: True
  IMS_PER_BATCH: 640
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  DISTANCE_METRIC: 'euclidian'
  PRETRAINED_CHECKPOINT_IDS: 13164
  
RE_RANKING:
  K1 : 20
  K2 : 6
  LAMBDA_VALUE : 0.3

DATASETS:
  NAMES: ('uav_mot')
  ROOT_DIR: ('/home/markoharalovic/CLIP-ReID/data/UAV_MOT')
OUTPUT_DIR: 'outputs/uav_mot/vit_clipreid/uav_mot_ft_from_scratch_20_30_epochs'

# CUDA_VISIBLE_DEVICES=0 python test_clipreid.py  --config_file configs/uav_mot/vit_clipreid.yml  TEST.WEIGHT checkpoints/VehicleID_clipreid_ViT-B-16_60.pth
# CUDA_VISIBLE_DEVICES=0 python train_clipreid.py --config_file configs/uav_mot/vit_clipreid.yml